/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ListsIdRouteImport } from './routes/lists.$id'
import { Route as ApiPublicHooksCheckAlertsRouteImport } from './routes/api/public/hooks/check-alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIdRoute = ListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListsRoute,
} as any)
const ApiPublicHooksCheckAlertsRoute =
  ApiPublicHooksCheckAlertsRouteImport.update({
    id: '/api/public/hooks/check-alerts',
    path: '/api/public/hooks/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lists': typeof ListsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lists/$id': typeof ListsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/lists/': typeof ListsIndexRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lists/$id': typeof ListsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/lists': typeof ListsIndexRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lists': typeof ListsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lists/$id': typeof ListsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/lists/': typeof ListsIndexRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lists'
    | '/onboarding'
    | '/pantry'
    | '/plan'
    | '/sitemap.xml'
    | '/lists/$id'
    | '/product/$id'
    | '/lists/'
    | '/api/public/hooks/check-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pantry'
    | '/plan'
    | '/sitemap.xml'
    | '/lists/$id'
    | '/product/$id'
    | '/lists'
    | '/api/public/hooks/check-alerts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lists'
    | '/onboarding'
    | '/pantry'
    | '/plan'
    | '/sitemap.xml'
    | '/lists/$id'
    | '/product/$id'
    | '/lists/'
    | '/api/public/hooks/check-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ListsRoute: typeof ListsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PantryRoute: typeof PantryRoute
  PlanRoute: typeof PlanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicHooksCheckAlertsRoute: typeof ApiPublicHooksCheckAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$id': {
      id: '/lists/$id'
      path: '/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ListsIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/api/public/hooks/check-alerts': {
      id: '/api/public/hooks/check-alerts'
      path: '/api/public/hooks/check-alerts'
      fullPath: '/api/public/hooks/check-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListsRouteChildren {
  ListsIdRoute: typeof ListsIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsIdRoute: ListsIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ListsRoute: ListsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PantryRoute: PantryRoute,
  PlanRoute: PlanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicHooksCheckAlertsRoute: ApiPublicHooksCheckAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
